[JENKINS-31681] Remove maven optional setting from token-macro dependency
As reported in the issue, installation on fresh Jenkins triggers
java.lang.NoClassDefFoundError: org/jenkinsci/plugins/tokenmacro/MacroEvaluationException

None of current "token-consumer" has token-macro dependency optional,
so this change goes along with common usage/knowledge.